#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'miniMaxSum' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def miniMaxSum(arr):
    a = arr[0]
    b = arr[1]
    c = arr[2]
    d = arr[3]
    e = arr[4]
    
    sum1 = a + b + c + d
    sum2 = b + c + d + e
    sum3 = c + d + e + a
    sum4 = d + e + a + b
    sum5 = e + a + b + c
    
    listsum = [sum1, sum2, sum3, sum4, sum5]
    
    minimum = min(listsum)
    maximum = max(listsum)
    
    print(minimum,maximum)

if __name__ == '__main__':
    arr = list(map(int, input().rstrip().split()))
    miniMaxSum(arr)
